"""Pydantic schemas for Week 5 / Day 24 — Grounded RAG and anti-hallucination.

Day 24 keeps the Day 22 baseline and the Day 23 improved pipeline untouched
and adds a *grounded* mode that can prove its answer with retrieved chunks:

    question -> Day 23 improved retrieval -> grounding gate
             -> (refuse) OR (grounded LLM -> structured evidence)
             -> citation validator -> answer + sources + verifiable quotes

The models here are the contract shared by the grounding service, the HTTP
endpoints, the evaluation services and the UI.

A key invariant of the whole module: source metadata (file name, page,
section, message ids) is NEVER taken from the LLM. The LLM may only reference
a ``chunk_id`` that was present in the context; the backend attaches the real
metadata from the retrieved chunk.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator

from app.schemas.day22 import EvaluationQuestion
from app.schemas.day23 import Day23Settings, ImprovedCandidate, RewriteInfo

# ----------------------------------------------------------------------
# Modes and statuses
# ----------------------------------------------------------------------
MODE_GROUNDED = "grounded"

STATUS_ANSWERED = "answered"
STATUS_INSUFFICIENT_CONTEXT = "insufficient_context"
STATUS_GROUNDING_FAILED = "grounding_failed"

GROUNDED_STATUSES = (
    STATUS_ANSWERED,
    STATUS_INSUFFICIENT_CONTEXT,
    STATUS_GROUNDING_FAILED,
)

# ----------------------------------------------------------------------
# Grounding gate reasons
# ----------------------------------------------------------------------
GATE_PASSED = "passed"
GATE_NO_ACCEPTED_CONTEXT = "no_accepted_context"
GATE_BELOW_ANSWER_THRESHOLD = "best_score_below_answer_threshold"

# ----------------------------------------------------------------------
# Citation validation errors (stable — tests and the UI depend on them)
# ----------------------------------------------------------------------
ERR_CITATION_NOT_IN_CONTEXT = "citation_not_in_context"
ERR_CHUNK_ID_NOT_FOUND = "chunk_id_not_found"
ERR_EMPTY_QUOTE = "empty_quote"
ERR_QUOTE_NOT_IN_CHUNK = "quote_not_in_chunk"
ERR_ANSWER_WITHOUT_EVIDENCE = "answer_without_evidence"
ERR_INVALID_MODEL_OUTPUT = "invalid_model_output"

# Default refusal wording. The grounding gate uses it when the LLM is never
# called; the LLM may provide its own message otherwise.
INSUFFICIENT_MESSAGE = (
    "Я не знаю: в загруженной базе недостаточно релевантной информации, "
    "чтобы надёжно ответить."
)
INSUFFICIENT_CLARIFICATION = (
    "Уточните вопрос или добавьте больше деталей (модель, узел, условие "
    "эксплуатации)."
)
GROUNDING_FAILED_MESSAGE = (
    "Ответ был сгенерирован, но evidence validation не прошла. "
    "Такой ответ нельзя считать подтверждённым источниками."
)

MAX_QUESTION_LENGTH = 2000


# ----------------------------------------------------------------------
# Source / citation models
# ----------------------------------------------------------------------
class GroundedMessageLink(BaseModel):
    """One message of a Telegram conversation chunk and its permalink.

    ``is_cited`` marks the message the validated quote was actually taken
    from (the main link). Other entries are context links.
    """

    message_id: int
    url: str | None = None
    is_cited: bool = False


class GroundedSource(BaseModel):
    """A real source, reconstructed from retrieved chunk metadata.

    Only fields that actually exist on the chunk are populated; the LLM can
    never add a field here.

    Day 24 addition: ``url`` is resolved by the backend *after* citation
    validation (never generated by the LLM). When no reliable permalink can
    be built it stays ``None`` and the UI shows a non-clickable source.
    """

    source_type: str
    source: str = ""
    chunk_id: str
    title: str = ""
    section: str = ""
    page: int | None = None
    page_from: int | None = None
    page_to: int | None = None
    message_ids: list[int] = Field(default_factory=list)
    date_from: str = ""
    date_to: str = ""
    chat_name: str = ""

    # Backend-resolved source link (optional; None when unavailable).
    url: str | None = None
    cited_message_id: int | None = None
    topic_id: int | None = None
    link_kind: str = ""
    link_note: str = ""
    context_links: list[GroundedMessageLink] = Field(default_factory=list)


class GroundedCitation(BaseModel):
    """One piece of evidence: a chunk_id + a quote + its validation result.

    ``quote_valid`` and ``validation_errors`` are produced by the backend
    CitationValidator, never by the LLM.
    """

    chunk_id: str
    quote: str
    quote_valid: bool
    validation_errors: list[str] = Field(default_factory=list)

    # Real metadata copied from the retrieved chunk (backend-owned).
    source_type: str = ""
    source: str = ""
    title: str = ""
    section: str = ""
    page: int | None = None
    page_from: int | None = None
    page_to: int | None = None
    message_ids: list[int] = Field(default_factory=list)
    date_from: str = ""
    date_to: str = ""
    chat_name: str = ""

    # The full retrieved chunk text ("Show full chunk" in the UI).
    chunk_text: str = ""

    # Backend-resolved source link (optional; None when unavailable).
    url: str | None = None
    cited_message_id: int | None = None
    topic_id: int | None = None
    link_kind: str = ""
    link_note: str = ""
    context_links: list[GroundedMessageLink] = Field(default_factory=list)

    def as_source(self) -> GroundedSource:
        return GroundedSource(
            source_type=self.source_type,
            source=self.source,
            chunk_id=self.chunk_id,
            title=self.title,
            section=self.section,
            page=self.page,
            page_from=self.page_from,
            page_to=self.page_to,
            message_ids=list(self.message_ids),
            date_from=self.date_from,
            date_to=self.date_to,
            chat_name=self.chat_name,
            url=self.url,
            cited_message_id=self.cited_message_id,
            topic_id=self.topic_id,
            link_kind=self.link_kind,
            link_note=self.link_note,
            context_links=list(self.context_links),
        )


# ----------------------------------------------------------------------
# Retrieval trace (the full Day 23 candidate trace is preserved)
# ----------------------------------------------------------------------
class GroundedRetrieval(BaseModel):
    """Retrieval + gate trace shown in the UI (debug / demo)."""

    rewritten_query: str = ""
    rewrite: RewriteInfo | None = None
    retrieval_top_k: int = 0
    final_top_k: int = 0
    similarity_threshold: float = 0.0
    answer_threshold: float = 0.0

    gate_passed: bool = False
    gate_reason: str = ""
    best_score: float | None = None
    accepted_count: int = 0
    rejected_count: int = 0
    retrieved_count: int = 0
    context_count: int = 0

    retrieved_candidates: list[ImprovedCandidate] = Field(default_factory=list)
    accepted_candidates: list[ImprovedCandidate] = Field(default_factory=list)
    rejected_candidates: list[ImprovedCandidate] = Field(default_factory=list)
    context_chunks: list[ImprovedCandidate] = Field(default_factory=list)


# ----------------------------------------------------------------------
# Grounded answer
# ----------------------------------------------------------------------
class GroundedRAGResult(BaseModel):
    """Structured result of one grounded RAG request."""

    status: Literal["answered", "insufficient_context", "grounding_failed"]
    question: str
    answer: str | None = None
    message: str | None = None
    clarification_request: str | None = None

    grounding_valid: bool = False
    sources: list[GroundedSource] = Field(default_factory=list)
    citations: list[GroundedCitation] = Field(default_factory=list)
    validation_errors: list[str] = Field(default_factory=list)

    # Anti-hallucination bookkeeping: True only when the generation provider
    # was actually invoked for this request.
    llm_called: bool = False

    model: str = ""
    generation_provider: str = ""
    temperature: float = 0.0
    embedding_model: str = ""
    index_path: str = ""
    chunking: str = ""
    finish_reason: str | None = None

    retrieval: GroundedRetrieval = Field(default_factory=GroundedRetrieval)
    pipeline: list[str] = Field(default_factory=list)


# ----------------------------------------------------------------------
# API requests / status
# ----------------------------------------------------------------------
def _strip_question(value: str) -> str:
    value = (value or "").strip()
    if not value:
        raise ValueError("question must not be blank")
    return value


class Day24AskRequest(Day23Settings):
    """Grounded ask request reuses the Day 23 retrieval knobs.

    ``similarity_threshold`` doubles as the answer gate (Option A, see
    docs/week5/day24.md): a chunk that is not relevant enough for retrieval
    must not be relevant enough to justify an answer.
    """

    question: str = Field(min_length=1, max_length=MAX_QUESTION_LENGTH)

    @field_validator("question")
    @classmethod
    def _strip(cls, value: str) -> str:
        return _strip_question(value)


class Day24StatusResponse(BaseModel):
    generation_provider: str
    generation_model: str
    temperature: float
    embedding_model: str
    index_path: str
    chunking: str
    default_retrieval_top_k: int
    default_final_top_k: int
    default_similarity_threshold: float
    answer_threshold: float
    retrieval_top_k_max: int
    final_top_k_max: int
    rewrite_provider: str
    rewrite_model: str
    demo_question_manual: str
    demo_question_telegram: str
    demo_question_insufficient: str
    index_exists: bool
    chunks: int = 0
    chunks_by_source_type: dict[str, int] = Field(default_factory=dict)


# ----------------------------------------------------------------------
# Evaluation (same 10 questions, automatic grounded checks + manual grade)
# ----------------------------------------------------------------------
class Day24EvaluationSummary(BaseModel):
    total_questions: int
    evaluated: int
    sources_present: int = 0
    quotes_present: int = 0
    quotes_valid: int = 0
    grounding_valid: int = 0
    answered: int = 0
    insufficient_context: int = 0
    grounding_failed: int = 0
    supported: dict[str, int] = Field(default_factory=dict)


class Day24EvaluationChecks(BaseModel):
    """Automatic, deterministic checks over one grounded answer."""

    status: str
    has_sources: bool
    has_quotes: bool
    all_quotes_valid: bool
    grounding_valid: bool


class Day24EvaluationRunResponse(BaseModel):
    question: EvaluationQuestion
    result: GroundedRAGResult
    checks: Day24EvaluationChecks


class Day24EvaluationRunAllResponse(BaseModel):
    runs: list[Day24EvaluationRunResponse] = Field(default_factory=list)
    summary: "Day24EvaluationSummary | None" = None


class Day24EvaluationGradeRecord(BaseModel):
    """One persisted evaluation row.

    ``answer_supported_by_evidence`` is the ONLY human field
    (PASS/PARTIAL/FAIL assigned by the user). The remaining fields are
    written automatically by the evaluation service after each grounded run
    so the summary can be recomputed without re-running the LLM.
    """

    answer_supported_by_evidence: Literal["pass", "partial", "fail"] | None = None

    # Automatic (backend-owned) fields, overwritten on every run.
    status: str | None = None
    has_sources: bool | None = None
    has_quotes: bool | None = None
    all_quotes_valid: bool | None = None
    grounding_valid: bool | None = None


class Day24EvaluationResultsResponse(BaseModel):
    results: dict[str, Day24EvaluationGradeRecord] = Field(default_factory=dict)
    summary: Day24EvaluationSummary


# ----------------------------------------------------------------------
# Negative evaluation (deterministic refusals)
# ----------------------------------------------------------------------
class Day24NegativeQuestion(BaseModel):
    id: str
    question: str
    note: str = ""
    expected_status: str = STATUS_INSUFFICIENT_CONTEXT


class Day24NegativeRunResponse(BaseModel):
    question: Day24NegativeQuestion
    expected_status: str
    actual_status: str
    llm_called: bool
    passed: bool
    best_score: float | None = None
    answer_threshold: float = 0.0


class Day24NegativeRunAllResponse(BaseModel):
    runs: list[Day24NegativeRunResponse] = Field(default_factory=list)


class Day24NegativeReport(BaseModel):
    questions: int = 0
    correctly_refused: int = 0
    incorrectly_answered: int = 0
    llm_invoked: int = 0
    runs: list[Day24NegativeRunResponse] = Field(default_factory=list)
